#!/bin/sh
#
#	$Id: undeadly_htdig,v 1.1.1.1 2004/08/16 20:26:33 dhartmei Exp $

WWW=/var/www/htdocs/undeadly.org
DATA=${WWW}/data
BIN=${WWW}/htdig/bin
CONF=${WWW}/htdig/conf/htdig.conf
DB=${WWW}/htdig/db

if [ X"${1}" != X"articles" -a X"${1}" != X"comments" ]; then
	echo "usage: `basename ${0}` ( articles | comments )"
	exit 1
fi

rm -rf ${DB}/*

if [ X"${1}" == X"articles" ]; then
	echo htdig articles
	time find ${DATA} -maxdepth 2 -name article \
		-a \! -path '*submissions*' | \
			sed s-/var/www/htdocs/-http://- | \
			${BIN}/htdig -i -s -c ${CONF} -m -
else
	echo htdig comments
	time find ${DATA} \( -name article -o -name comment \) \
		-a \! -path '*submissions*' | \
			sed s-/var/www/htdocs/-http://- | \
			${BIN}/htdig -i -s -c ${CONF} -m -
fi

echo
echo htmerge
time LC_COLLATE=C ${BIN}/htmerge -s -c ${CONF}

echo
echo htfuzzy endings
time ${BIN}/htfuzzy -c ${CONF} endings

echo
echo htfuzzy synonyms
time ${BIN}/htfuzzy -c ${CONF} synonyms

echo
echo replacing database files
mv ${DB}/* ${DB}_${1}

